# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Program File\Jupyter-NoteBook\Graduation Project\GraProject-release-0.3\Graproject.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1028, 993)
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(18)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/人脸识别系统.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{ \n"
"    border-image: url(back_pic3.jpg); \n"
"    } \n"
"    #centralwidge * { \n"
"    border-image:url(); \n"
"    }")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ShowFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShowFrame.sizePolicy().hasHeightForWidth())
        self.ShowFrame.setSizePolicy(sizePolicy)
        self.ShowFrame.setMinimumSize(QtCore.QSize(600, 600))
        self.ShowFrame.setMaximumSize(QtCore.QSize(1500, 1500))
        self.ShowFrame.setBaseSize(QtCore.QSize(700, 500))
        self.ShowFrame.setStyleSheet("")
        self.ShowFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.ShowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ShowFrame.setObjectName("ShowFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ShowFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ShowImgLabel = QtWidgets.QLabel(self.ShowFrame)
        self.ShowImgLabel.setMinimumSize(QtCore.QSize(590, 590))
        self.ShowImgLabel.setText("")
        self.ShowImgLabel.setObjectName("ShowImgLabel")
        self.gridLayout_3.addWidget(self.ShowImgLabel, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.ShowFrame)
        self.InfoOutputFrame = QtWidgets.QFrame(self.centralwidget)
        self.InfoOutputFrame.setMinimumSize(QtCore.QSize(250, 400))
        self.InfoOutputFrame.setMaximumSize(QtCore.QSize(400, 800))
        self.InfoOutputFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.InfoOutputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InfoOutputFrame.setObjectName("InfoOutputFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.InfoOutputFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LoadMsg = QtWidgets.QPushButton(self.InfoOutputFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadMsg.sizePolicy().hasHeightForWidth())
        self.LoadMsg.setSizePolicy(sizePolicy)
        self.LoadMsg.setMaximumSize(QtCore.QSize(400, 100))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/启动.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LoadMsg.setIcon(icon1)
        self.LoadMsg.setObjectName("LoadMsg")
        self.verticalLayout_3.addWidget(self.LoadMsg)
        self.MsgFrame = QtWidgets.QFrame(self.InfoOutputFrame)
        self.MsgFrame.setMinimumSize(QtCore.QSize(200, 400))
        self.MsgFrame.setMaximumSize(QtCore.QSize(400, 800))
        self.MsgFrame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.MsgFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MsgFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MsgFrame.setObjectName("MsgFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.MsgFrame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.MsgEdit = QtWidgets.QTextEdit(self.MsgFrame)
        self.MsgEdit.setMinimumSize(QtCore.QSize(200, 400))
        self.MsgEdit.setMaximumSize(QtCore.QSize(400, 800))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.MsgEdit.setFont(font)
        self.MsgEdit.setStyleSheet("color :\'white\'")
        self.MsgEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MsgEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.MsgEdit.setReadOnly(True)
        self.MsgEdit.setObjectName("MsgEdit")
        self.verticalLayout_9.addWidget(self.MsgEdit)
        self.verticalLayout_3.addWidget(self.MsgFrame)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.addWidget(self.InfoOutputFrame)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.ControlFrame = QtWidgets.QFrame(self.centralwidget)
        self.ControlFrame.setMaximumSize(QtCore.QSize(2800, 300))
        self.ControlFrame.setAutoFillBackground(True)
        self.ControlFrame.setStyleSheet("")
        self.ControlFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.ControlFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ControlFrame.setObjectName("ControlFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ControlFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.ControlFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.camera_model = QtWidgets.QRadioButton(self.ControlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_model.sizePolicy().hasHeightForWidth())
        self.camera_model.setSizePolicy(sizePolicy)
        self.camera_model.setMinimumSize(QtCore.QSize(150, 40))
        self.camera_model.setMaximumSize(QtCore.QSize(1500, 1500))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.camera_model.setFont(font)
        self.camera_model.setTabletTracking(True)
        self.camera_model.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.camera_model.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/摄像头.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.camera_model.setIcon(icon2)
        self.camera_model.setObjectName("camera_model")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.camera_model)
        self.gridLayout.addWidget(self.camera_model, 0, 2, 1, 1)
        self.video_model = QtWidgets.QRadioButton(self.ControlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_model.sizePolicy().hasHeightForWidth())
        self.video_model.setSizePolicy(sizePolicy)
        self.video_model.setMinimumSize(QtCore.QSize(150, 40))
        self.video_model.setMaximumSize(QtCore.QSize(1500, 1500))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.video_model.setFont(font)
        self.video_model.setTabletTracking(True)
        self.video_model.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/视频-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.video_model.setIcon(icon3)
        self.video_model.setObjectName("video_model")
        self.buttonGroup.addButton(self.video_model)
        self.gridLayout.addWidget(self.video_model, 0, 1, 1, 1)
        self.pic_model = QtWidgets.QRadioButton(self.ControlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pic_model.sizePolicy().hasHeightForWidth())
        self.pic_model.setSizePolicy(sizePolicy)
        self.pic_model.setMinimumSize(QtCore.QSize(150, 40))
        self.pic_model.setMaximumSize(QtCore.QSize(1500, 1500))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.pic_model.setFont(font)
        self.pic_model.setTabletTracking(True)
        self.pic_model.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pic_model.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/图片.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pic_model.setIcon(icon4)
        self.pic_model.setObjectName("pic_model")
        self.buttonGroup.addButton(self.pic_model)
        self.gridLayout.addWidget(self.pic_model, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.LocalCamera = QtWidgets.QCheckBox(self.ControlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LocalCamera.sizePolicy().hasHeightForWidth())
        self.LocalCamera.setSizePolicy(sizePolicy)
        self.LocalCamera.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.LocalCamera.setFont(font)
        self.LocalCamera.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LocalCamera.setAutoFillBackground(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/本地摄像头.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LocalCamera.setIcon(icon5)
        self.LocalCamera.setCheckable(True)
        self.LocalCamera.setChecked(False)
        self.LocalCamera.setObjectName("LocalCamera")
        self.verticalLayout_2.addWidget(self.LocalCamera)
        self.label_2 = QtWidgets.QLabel(self.ControlFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.OpenPath = QtWidgets.QLineEdit(self.ControlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenPath.sizePolicy().hasHeightForWidth())
        self.OpenPath.setSizePolicy(sizePolicy)
        self.OpenPath.setMinimumSize(QtCore.QSize(200, 20))
        self.OpenPath.setMaximumSize(QtCore.QSize(1500, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.OpenPath.setFont(font)
        self.OpenPath.setReadOnly(True)
        self.OpenPath.setObjectName("OpenPath")
        self.horizontalLayout.addWidget(self.OpenPath)
        self.OpenPathBt = QtWidgets.QPushButton(self.ControlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenPathBt.sizePolicy().hasHeightForWidth())
        self.OpenPathBt.setSizePolicy(sizePolicy)
        self.OpenPathBt.setMinimumSize(QtCore.QSize(40, 20))
        self.OpenPathBt.setMaximumSize(QtCore.QSize(1500, 20))
        self.OpenPathBt.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/打开文件.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenPathBt.setIcon(icon6)
        self.OpenPathBt.setObjectName("OpenPathBt")
        self.horizontalLayout.addWidget(self.OpenPathBt)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.StartBt = QtWidgets.QPushButton(self.ControlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartBt.sizePolicy().hasHeightForWidth())
        self.StartBt.setSizePolicy(sizePolicy)
        self.StartBt.setMaximumSize(QtCore.QSize(120, 60))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/人脸识别.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StartBt.setIcon(icon7)
        self.StartBt.setObjectName("StartBt")
        self.buttonGroup.addButton(self.StartBt)
        self.horizontalLayout_2.addWidget(self.StartBt)
        self.StopBt = QtWidgets.QPushButton(self.ControlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopBt.sizePolicy().hasHeightForWidth())
        self.StopBt.setSizePolicy(sizePolicy)
        self.StopBt.setMaximumSize(QtCore.QSize(120, 60))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icon/暂停.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StopBt.setIcon(icon8)
        self.StopBt.setObjectName("StopBt")
        self.buttonGroup.addButton(self.StopBt)
        self.horizontalLayout_2.addWidget(self.StopBt)
        self.SaveBt = QtWidgets.QPushButton(self.ControlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveBt.sizePolicy().hasHeightForWidth())
        self.SaveBt.setSizePolicy(sizePolicy)
        self.SaveBt.setMaximumSize(QtCore.QSize(120, 60))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icon/保存.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveBt.setIcon(icon9)
        self.SaveBt.setObjectName("SaveBt")
        self.buttonGroup.addButton(self.SaveBt)
        self.horizontalLayout_2.addWidget(self.SaveBt)
        self.ExitBt = QtWidgets.QPushButton(self.ControlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExitBt.sizePolicy().hasHeightForWidth())
        self.ExitBt.setSizePolicy(sizePolicy)
        self.ExitBt.setMaximumSize(QtCore.QSize(120, 60))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icon/退出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExitBt.setIcon(icon10)
        self.ExitBt.setObjectName("ExitBt")
        self.horizontalLayout_2.addWidget(self.ExitBt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.frame = QtWidgets.QFrame(self.ControlFrame)
        self.frame.setMinimumSize(QtCore.QSize(481, 270))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 9, 461, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.SavePath = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SavePath.sizePolicy().hasHeightForWidth())
        self.SavePath.setSizePolicy(sizePolicy)
        self.SavePath.setMinimumSize(QtCore.QSize(200, 15))
        self.SavePath.setMaximumSize(QtCore.QSize(1500, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.SavePath.setFont(font)
        self.SavePath.setReadOnly(True)
        self.SavePath.setObjectName("SavePath")
        self.horizontalLayout_5.addWidget(self.SavePath)
        self.SavePathBt = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SavePathBt.sizePolicy().hasHeightForWidth())
        self.SavePathBt.setSizePolicy(sizePolicy)
        self.SavePathBt.setMinimumSize(QtCore.QSize(40, 20))
        self.SavePathBt.setMaximumSize(QtCore.QSize(1500, 20))
        self.SavePathBt.setText("")
        self.SavePathBt.setIcon(icon6)
        self.SavePathBt.setObjectName("SavePathBt")
        self.horizontalLayout_5.addWidget(self.SavePathBt)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 473, 19))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.IpPath = QtWidgets.QLineEdit(self.frame)
        self.IpPath.setGeometry(QtCore.QRect(10, 130, 400, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IpPath.sizePolicy().hasHeightForWidth())
        self.IpPath.setSizePolicy(sizePolicy)
        self.IpPath.setMaximumSize(QtCore.QSize(700, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.IpPath.setFont(font)
        self.IpPath.setAutoFillBackground(False)
        self.IpPath.setInputMask("")
        self.IpPath.setMaxLength(32767)
        self.IpPath.setFrame(True)
        self.IpPath.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.IpPath.setClearButtonEnabled(True)
        self.IpPath.setObjectName("IpPath")
        self.UserName = QtWidgets.QLineEdit(self.frame)
        self.UserName.setGeometry(QtCore.QRect(10, 160, 400, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserName.sizePolicy().hasHeightForWidth())
        self.UserName.setSizePolicy(sizePolicy)
        self.UserName.setMaximumSize(QtCore.QSize(700, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.UserName.setFont(font)
        self.UserName.setAutoFillBackground(False)
        self.UserName.setInputMask("")
        self.UserName.setMaxLength(32767)
        self.UserName.setFrame(True)
        self.UserName.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.UserName.setClearButtonEnabled(True)
        self.UserName.setObjectName("UserName")
        self.UserPwd = QtWidgets.QLineEdit(self.frame)
        self.UserPwd.setGeometry(QtCore.QRect(10, 190, 400, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserPwd.sizePolicy().hasHeightForWidth())
        self.UserPwd.setSizePolicy(sizePolicy)
        self.UserPwd.setMaximumSize(QtCore.QSize(700, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.UserPwd.setFont(font)
        self.UserPwd.setAutoFillBackground(False)
        self.UserPwd.setInputMask("")
        self.UserPwd.setMaxLength(32767)
        self.UserPwd.setFrame(True)
        self.UserPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.UserPwd.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.UserPwd.setClearButtonEnabled(True)
        self.UserPwd.setObjectName("UserPwd")
        self.ConfirmCameraBt = QtWidgets.QPushButton(self.frame)
        self.ConfirmCameraBt.setGeometry(QtCore.QRect(10, 220, 401, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfirmCameraBt.sizePolicy().hasHeightForWidth())
        self.ConfirmCameraBt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.ConfirmCameraBt.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icon/选择.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ConfirmCameraBt.setIcon(icon11)
        self.ConfirmCameraBt.setAutoDefault(False)
        self.ConfirmCameraBt.setDefault(True)
        self.ConfirmCameraBt.setFlat(False)
        self.ConfirmCameraBt.setObjectName("ConfirmCameraBt")
        self.horizontalLayout_3.addWidget(self.frame)
        self.verticalLayout_5.addWidget(self.ControlFrame)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1028, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人脸识别系统"))
        self.LoadMsg.setText(_translate("MainWindow", "程序模块启动加载"))
        self.label.setText(_translate("MainWindow", "请选择检测类别："))
        self.camera_model.setText(_translate("MainWindow", "摄像头"))
        self.video_model.setText(_translate("MainWindow", "视频"))
        self.pic_model.setText(_translate("MainWindow", "图片"))
        self.LocalCamera.setText(_translate("MainWindow", "本地摄像头"))
        self.label_2.setText(_translate("MainWindow", "文件打开路径："))
        self.StartBt.setText(_translate("MainWindow", "开始识别"))
        self.StopBt.setText(_translate("MainWindow", "暂停"))
        self.SaveBt.setText(_translate("MainWindow", "保存"))
        self.ExitBt.setText(_translate("MainWindow", "退出程序"))
        self.label_4.setText(_translate("MainWindow", "（文件保存路径默认为SaveData文件夹）"))
        self.label_5.setText(_translate("MainWindow", "文件保存路径："))
        self.label_6.setText(_translate("MainWindow", "输入以下信息连接IP摄像头:"))
        self.IpPath.setPlaceholderText(_translate("MainWindow", "请输入摄像头IP地址"))
        self.UserName.setPlaceholderText(_translate("MainWindow", "请输入摄像头用户名"))
        self.UserPwd.setPlaceholderText(_translate("MainWindow", "请输入摄像头用户密码"))
        self.ConfirmCameraBt.setText(_translate("MainWindow", "确认连接摄像头"))
        self.label_3.setText(_translate("MainWindow", "copyright©DD4"))

